name: Rust NEAR Contract and Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      
      # build.sh is run as part of sandbox testing.
      # - name: Build Rust Contract
      #   run: ./scripts/build.sh
      #   shell: bash
      
      - name: Lint & Clippy
        run: cargo fmt --check && cargo clippy --all-targets --verbose -- -D warnings

      - name: Run Rust tests
        run: ./scripts/test.sh
        shell: bash

  nodejs-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ts-lib

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Run Tests
        run: npm test
