name: Contract Sandbox Test

on:
  push:
    branches: [ main ]

jobs:
  rust-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Sandbox Test
        run: |
          rustup target add wasm32-unknown-unknown
          cargo build --target wasm32-unknown-unknown
          cd sandbox-rs
          cargo run --example sandbox "../target/wasm32-unknown-unknown/debug/neareth.wasm"
